### ISSUE TITLE
Doesn't work with higher times

### ISSUE THREAD

**Issue by StamKaly** [andrewboltachev/timecalc#1]
input:  15:00+17:00
32:00

input: 00:00-23:00
-23:00

Can you please make it respond with: 06:00 for the first and 01:00 for the second like a real time calculator?

**Comment by andrewboltachev** [comment]
@StamKaly added this as `--real` argument. 1st one is 08:00 though :-)

**Comment by StamKaly** [comment]
Thsnks!

**Comment by StamKaly** [comment]
Thsnks!
